version: '3'

services:
  mi_docker_base:
    build: .
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    command: jupyter-lab --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''